# Generated by Django 2.2 on 2020-07-01 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('RUT', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('comuna', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('RUT', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('RUT', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto_final', models.IntegerField()),
                ('descuento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('web', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('RUT', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('RUT', models.IntegerField(primary_key=True, serialize=False)),
                ('telefono', models.IntegerField()),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.Direccion')),
            ],
        ),
    ]
